### ISSUE TITLE
Arguments for allowing explicit variables?

### ISSUE THREAD

**Issue by rleegates** [blegat/MultivariatePolynomials.jl#33]
What are the arguments in favor of allowing explicit variables? 

I would expect it to be more efficient to fix the number of variables as a type-parameter `NV`, to store the exponents as `SVector{NV,Int}`, and to only allow arithmetic on polynomials with the same `NV`. This way there should be no problem with evaluation order, as there is only the canonical ordering. Evaluating a `NV`-Polynomial at `NV` polynomials of `MV` variables should then always return an `MV`-polynomial. Perhaps it would provide for other simplifications. 

The reason for my question is that I have never encountered a case in which I do not know the variables of all my polynomials beforehand (they are always coordinates for a chart on an `NV`-manifold), i.e. `x*y = [1,0]*[0,1] = [1,1]`, nor do I ever care if these have "names", i.e. `Symbol`s, attached to them.

**Comment by blegat** [comment]
In the near future, the implementation of this package will go to [DynamicPolynomials.jl](https://github.com/blegat/DynamicPolynomials.jl) and this package will contain code that defines the interface for multivariate polynomials and code that is independent to the implementation of the polynomial. `TypedPolynomials` will be the implementation of choice if you want to use more information when compiling to get faster run time but `DynamicPolynomials` will still be around. Any other implementation could also be easily added. 

If you have `NV` variables then with either `TypedPolynomials` or `MultivariatePolynomials` you can do
```
@polyvar x[1:NV]
```
(although in `TypedPolynomials` you currently need to use literals like `@polyvar x[1:8]`)
They will have names `x1`, ..., `xNV` but these names does not matter so much, they are only used as an id to check that they are different.
[TypedPolynomials](https://github.com/rdeits/TypedPolynomials.jl) stores the exponents [in an `NTuple`](https://github.com/rdeits/TypedPolynomials.jl/blob/85c46b28ff694901aa5671631bb3013db8276ffb/src/types.jl#L9).

What makes your idea impossible to implement in `DynamicPolynomials` is the fact that we want to make it possible to build the polynomial from scratch (like with `3 * x + 2 * x * y^2`). Because of this we need to define a type for variable, monomial, term and polynomials and type stable operations between them. For the operation of multiplying a polynomial with a variable to be type stable, we need no be able to know the return type just by looking at the types of the input. However, if you have a polynomial of `N` variables and a variable, since you do not know if this variable is among the `N` variables of you polynomial, you cannot know if your polynomial is going to have `N` or `N+1` variable.
Even if you know that at then end of the day all your polynomials will have `NV` variable, during their construction they still have to go from `1` to `NV`.

You could define a new implementation where you only define the polynomial type and not the term, monomial and variable type. Then indeed you would just have
```julia
type SimplePolynomials{NV, T}
   a::SVector{NV, T}
end
```
however, using `TypedPolynomials` will be just as fast so I don't think it is worth it :)

**Comment by rleegates** [comment]
Yes, I understood the idea of being able to build polynomials from scratch, and this is still possible if the total number of variables is known beforehand (which is sensible, since they are usually the coordinates of some space).

I made a [small module demonstrating the basics](https://gist.github.com/rleegates/44e5838e8c3089ea277c70b655f21259) (I haven't checked everything and the operators are probably quite inefficient, so handle with care).
