### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by saschatimme** [blegat/MultivariatePolynomials.jl#42]
I need a good multivariate polynomial implementation for two of my projects (especially fast evaluation).
So I would like to contribute to get the project in a stable state :) But I am a little bit confused about the current state. I read the PRs, saw `TypedPolynomials`, `DynamicPolynomials` and also your `typed` branch.
Could you maybe elaborate your current plans and maybe where you would need help?

**Comment by blegat** [comment]
Thanks for your interest in this package !
It used to contain the implementation of DynamicPolynomials. However, @rdeits suggested a new implementation with TypedPolynomials that was a lot faster. Its approach consists in having the list of variables of the polynomial/term/monomial as a parameter of the type. This means that Julia will compile a specific function for each list of variables and that the list of exponents of a monomial could also be stored as a tuple which makes many operation use less allocation and be faster.
Once `typed` is merged, this package will be the definition of an API to use an implementation of polynomials.
Currently, DynamicPolynomials passes all the tests but TypedPolynomials remains to be ported to use the MultivariatePolynomials API. I am currently porting TypedPolynomials. It shouldn't take more than a few days.
In the meantime you can already try the API through DynamicPolynomials, it would help to know that you think of the API and whether you find any bug or missing feature. You can find how to use evaluation in `test/subs.jl` in the `typed` branch.

**Comment by blegat** [comment]
The typed branch of MultivariatePolynomials can now be used with the typed branch of TypedPolynomials.

**Comment by saschatimme** [comment]
This looks all really good!
I poked a little bit around and found some things:
* I think the implementations (`DynamicalPolynomials`, `TypedPolynomials`) need to reexport the exports from `MultivariatePolynomials`, otherwise e.g. `using DynamicPolynomials` wouldn't make the functions from `MultivariatePolynomials` available (so `coefficients(f)` would throw but `DP.coefficients(f)` would work)
* I found some small things (pretty printing with complex coefficients looks wrong, degree w.r.t to a specific variable would be nice) which I can add once everything is merged etc.

Another point is the evaluation API:
Let's assume we have a system of polynomials `F` with `n` variables, which is called often in different functions. These functions shouldn't really need to care about the names of the variables, but only about the number of variables. As I understand the AP, we would have to pass the variables together with the polynomial around right?

Somewhat related, with TypedPolynomials, if I have a vector of polynomials could it be that the elements of the have different types, right? (Assume `@polyvar x y z' and the system `[x, y, z]`). 
Wouldn't this trip up the type inference?

As a last thing, is the longterm plan to embrace different implementations or more like e.g. JuliaPlots   where we choose a default implementation which is shipped under the MultivariatePolynomials.jl package?

Let me know if you have some specific things where I can help out.

**Comment by blegat** [comment]
> I found some small things (pretty printing with complex coefficients looks wrong, degree w.r.t to a specific variable would be nice) which I can add once everything is merged etc.

Thanks, that will be welcome !

> Let's assume we have a system of polynomials `F` with `n` variables, which is called often in different functions. These functions shouldn't really need to care about the names of the variables, but only about the number of variables. As I understand the AP, we would have to pass the variables together with the polynomial around right?

If you only pass the vector of values, e.g. `p((1, 2, 3))`, you assume an order between the variables.
For example you assume that `x` will be `1`, `y` will be `2` and `z` will be `3`. However the implementation could have chosen to order them differently so it looks a bit dangerous.
Currently DynamicPolynomials order the variable by creation time and TypedPolynomials by alphabetical order.
Normally, if you do `p(variables(p) => (1, 2, 3))`, the implementation is expected to recognize that it is given exactly its vector of variables and do something faster. We do not transform `p((1, 2, 3))` into this form by default as you should do this only if you are sure that they will have this order. That is still up to debate though.

> Somewhat related, with TypedPolynomials, if I have a vector of polynomials could it be that the elements of the have different types, right? (Assume `@polyvar x y z' and the system `[x, y, z]`). 
> Wouldn't this trip up the type inference?

Yes, with TypedPolynomials, you would want to use tuples instead of vector to store a list of variables since the elements of a tuple can have different types.

> As a last thing, is the longterm plan to embrace different implementations or more like e.g. JuliaPlots   where we choose a default implementation which is shipped under the MultivariatePolynomials.jl package?

The situation is a bit different from JuliaPlots here. There a typically 2 situations.

1. You are writing a code that needs the user to input a polynomial, an algebraic set, ... and you don't want your function to be specific to an implementation but rather want to implement an algorithm that works with polynomials in an abstract way.
2. You want to create a polynomial to pass it to an algorithm implemented like in 1.

In 1., you will only use MultivariatePolynomials and you would prefer it to be as lightweight as possible so it is better if it does not include a default implementation.

> I think the implementations (`DynamicalPolynomials`, `TypedPolynomials`) need to reexport the exports from `MultivariatePolynomials`, otherwise e.g. `using DynamicPolynomials` wouldn't make the functions from `MultivariatePolynomials` available (so `coefficients(f)` would throw but `DP.coefficients(f)` would work)

If you are in case 2., you shouldn't need the API since you are just constructing the polynomial.

**Comment by saschatimme** [comment]
> Normally, if you do p(variables(p) => (1, 2, 3)), the implementation is expected to recognize that it is given exactly its vector of variables and do something faster. We do not transform p((1, 2, 3)) into this form by default as you should do this only if you are sure that they will have this order. That is still up to debate though.

I see the problem, personally I would lean to the current more verbose / less magic version.

> 1. You are writing a code that needs the user to input a polynomial, an algebraic set, ... and you don't want your function to be specific to an implementation but rather want to implement an algorithm that works with polynomials in an abstract way.
> 2. You want to create a polynomial to pass it to an algorithm implemented like in 1.

That makes total sense.

> >Somewhat related, with TypedPolynomials, if I have a vector of polynomials could it be that the elements of the have different types, right? (Assume @polyvar x y z' and the system[x, y, z]`).
Wouldn't this trip up the type inference?

> Yes, with TypedPolynomials, you would want to use tuples instead of vector to store a list of variables since the elements of a tuple can have different types.

Assume now that I would write a generic algorithm which works on a system of polynomials and I would choose to use a `Vector` to store these polynomials. Wouldn't that mean that my code would break / perform bad depending on the implementation? I mean the best would be to make such pitfalls impossible, but it's probably okay to just document such pitfalls.

Finally, I just wanted to let you know that I really appreciate that you take the time to discuss this here and to answer my questions :relaxed:

**Comment by blegat** [comment]
> Assume now that I would write a generic algorithm which works on a system of polynomials and I would choose to use a `Vector` to store these polynomials. Wouldn't that mean that my code would break / perform bad depending on the implementation? I mean the best would be to make such pitfalls impossible, but it's probably okay to just document such pitfalls.

Yes, we need to be clear about such things in the implementation. It is ok to make a vector of polynomials as long as you promote them to a common type.
In the following example, you can see that they have both been promoted to vectors with x, y and z:
```julia
julia> using TypedPolynomials
julia> @polyvar x y z
julia> eltype([x + y, y + z])
TypedPolynomials.Polynomial{Int64, TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{(x, y, z),3}},Array{TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{(x, y, z),3}},1}}
```

**Comment by rdeits** [comment]
Regarding polynomials with different types: I've tried to be pretty careful in TypedPolynomials to make sure that everything should work and be efficient without you needing to do any manual promotion. For example (with TypedPolynomials `master`):

```julia
julia> using TypedPolynomials

julia> @polyvar x y z
(x, y, z)

julia> v = [x, y]
2-element Array{TypedPolynomials.Monomial{(x, y),2},1}:
 x
 y
```

note that the element type has automatically been promoted to `Monomial{(x, y)}`, which is a "wide enough" type to hold both `x` and `y`. This is all implemented through Julia's built-in promotion mechanism, so that information is available for type inference. For example, if we write a function:

```julia
julia> f(x, y) = [x, y, x + y]
```

Then `@code_warntype f(x, y)` shows that the inferred output type is `Array{Polynomial{Term{Int64,Monomial{(x, y),2}},Array{Term{Int64,Monomial{(x, y),2}},1}},1}`, which means that every element in that vector has been inferrably promoted to a Polynomial in x and y.

**Comment by rdeits** [comment]
Oh, oops, I see that's exactly what @blegat was just saying. Sorry!

**Comment by rdeits** [comment]
@saschatimme I agree about re-exporting the symbols from MultivariatePolynomials in TypedPolynomials. I'm going to try using https://github.com/simonster/Reexport.jl to automate that.

**Comment by saschatimme** [comment]
I see that things get inferred most of the time, but here is a concrete use case where I had to help the type system a little bit:
```julia
import MultivariatePolynomials
const MP = MultivariatePolynomials 
import TypedPolynomials
const TP = TypedPolynomials

@TP.polyvar x y z

f = 3x^2-2y^2*x-y+3

# this makes f homgenous using the variable z
function homogenize_naive(f::MP.AbstractPolynomial, variable::MP.AbstractVariable)
    deg = MP.maxdeg(f)
    terms = MP.terms(f)
    newterms = map(term -> begin
        homvar_deg = deg - MP.deg(term)
        if homvar_deg == 0
            term
       else
            term * variable^homvar_deg
        end
    end, terms)
    MP.polynomial(newterms)
end


function homogenize(f::MP.AbstractPolynomial, variable::MP.AbstractVariable)
    deg = MP.maxdeg(f)
    terms = MP.terms(f)
    promoted_type = promote_type(typeof(variable), eltype(terms))
    newterms = map(term -> begin
        homvar_deg = deg - MP.deg(term)
        if homvar_deg == 0
            convert(promoted_type, term)
       else
            convert(promoted_type, term * variable^homvar_deg)
        end
    end, terms)
    MP.polynomial(newterms)
end

g = homogenize_naive(f, z)
@show typeof(g)

h = homogenize(f, z)
@show typeof(h)
```
Then we get
```julia
typeof(g) = TypedPolynomials.Polynomial{Int64,TypedPolynomials.Term{Int64,M} where M<:TypedPolynomials.Monomial,Array{TypedPolynomials.Term{Int64,M} where M<:TypedPolynomials.Monomial,1}}

typeof(h) = TypedPolynomials.Polynomial{Int64,TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{(x, y, z),3}},Array{TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{(x, y, z),3}},1}}
```

Or is there a way to write this without explicit promotions?

**Comment by blegat** [comment]
variable^0 doesn't work ?

**Comment by saschatimme** [comment]
Indeed, that did the trick.
